# Generated by Django 2.2.10 on 2020-05-17 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_type', models.CharField(max_length=25)),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('email_id', models.CharField(max_length=30, unique=True)),
                ('mobile_no', models.IntegerField(max_length=10, unique=True)),
                ('address', models.TextField()),
                ('pincode', models.IntegerField(max_length=6)),
                ('id_proof_doc_path', models.FileField(null=True, upload_to='owner_id')),
                ('password', models.CharField(max_length=100)),
                ('reg_date_time', models.DateTimeField(auto_now_add=True)),
                ('login_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('active_status', models.BooleanField(default=False)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.City')),
            ],
        ),
    ]
