# Generated by Django 2.2.10 on 2020-05-17 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('property_id', models.AutoField(primary_key=True, serialize=False)),
                ('property_name', models.CharField(max_length=30, unique=True)),
                ('property_identity_doc_path', models.FileField(upload_to='property_id')),
                ('address', models.TextField()),
                ('pincode', models.IntegerField(max_length=6)),
                ('description', models.TextField()),
                ('capacity', models.IntegerField(max_length=6)),
                ('normal_price', models.FloatField(max_length=10)),
                ('decoration_price', models.FloatField(max_length=10, null=True)),
                ('catering_price', models.FloatField(max_length=10, null=True)),
                ('is_property_verified', models.BooleanField(default=False)),
                ('active_status', models.BooleanField(default=False)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.City')),
            ],
        ),
        migrations.CreateModel(
            name='Property_Category',
            fields=[
                ('property_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('property_category_name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property_Vid',
            fields=[
                ('property_vid_id', models.AutoField(primary_key=True, serialize=False)),
                ('property_vid_path', models.FileField(null=True, upload_to='property_vid')),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.Property')),
            ],
        ),
        migrations.CreateModel(
            name='Property_Img',
            fields=[
                ('property_img_id', models.AutoField(primary_key=True, serialize=False)),
                ('property_img_path', models.ImageField(null=True, upload_to='property_img')),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.Property')),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='property_category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.Property_Category'),
        ),
        migrations.AddField(
            model_name='property',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
    ]
